replicaCount: 1

image:
  repository: mysql
  tag: 8.0
  pullPolicy: IfNotPresent

# This name is critical; it becomes the network hostname
appName: cardsdb

# Database initialization settings
db:
  name: cardsdb
  rootPassword: root

service:
  type: ClusterIP
  port: 3306
