apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "rabbitmq" }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name | default "rabbitmq" }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | default "rabbitmq" }}
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
            - containerPort: {{ .Values.managementPort }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.username }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.password }}"
