apiVersion: v1
kind: Service
metadata:
  name: { { .Values.name | default "rabbitmq" } }
spec:
  selector:
    app: { { .Values.name | default "rabbitmq" } }
  ports:
    - name: amqp
      port: { { .Values.port } }
      targetPort: { { .Values.port } }
    - name: management
      port: { { .Values.managementPort } }
      targetPort: { { .Values.managementPort } }
