apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
{{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: {{ .Values.managementService.port }}
      targetPort: management
      protocol: TCP
  selector:
{{- include "rabbitmq.selectorLabels" . | nindent 4 }}
