apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "cardsdb" }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name | default "cardsdb" }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | default "cardsdb" }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.rootPassword }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.database }}"
