apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName | quote }}
  labels:
    app: {{ .Values.appName | quote }}
spec:
  selector:
    app: {{ .Values.appName | quote }}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
