apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "accountsdb" }}
spec:
  selector:
    app: {{ .Values.name | default "accountsdb" }}
  ports:
    - port: 3306
      targetPort: 3306