apiVersion: v1
kind: Service
metadata:
  name: { { .Values.name | default "cardsdb" } }
spec:
  selector:
    app: { { .Values.name | default "cardsdb" } }
  ports:
    - port: 3306
      targetPort: 3306
