# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: karthikkaliki/loans
  tag: v10

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false

# Ensure ${build.version} can be resolved by setting a global buildVersion
# These values will propagate to the common configmap when this chart is used in an umbrella chart
global:
  buildVersion: "s14"
  loansDBHost: "loansdb"
  dbUsername: "root"
  dbPassword: "root"

# Optional: explicit datasource properties (some deployments prefer explicit overrides)
spring:
  datasource:
    url: "jdbc:mysql://loansdb:3306/loansdb"
    username: "root"
    password: "root"
# Extra env vars to request from the common ConfigMap

