replicaCount: 1

image:
  repository: rabbitmq
  tag: "3.12-management" # management tag is required for the web UI
  pullPolicy: IfNotPresent

# Messaging Port (AMQP)
service:
  type: ClusterIP
  port: 5672

# Management Dashboard Port
managementService:
  type: LoadBalancer # Set to LoadBalancer if you want to access the UI from your browser
  port: 15672

persistence:
  enabled: true
  storageClass: "" # Leave empty for default, or match your Kafka storageClass
  size: 1Gi

podSecurityContext:
  fsGroup: 999 # RabbitMQ default user group is 999

rabbitmq:
  # These credentials match what your microservices expect
  username: "user"
  password: "password"
  # This matches the 'rabbitHost' variable in your global config
  hostname: "rabbitmq"

resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "500m"
